---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ingress-nginx
  name: ingress-nginx-controller
data:
  ssl-ciphers: ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384
  ssl-protocols: TLSv1.2 TLSv1.3
  hsts-max-age: "31536000"
  hsts-preload: "true"
  ssl-redirect: "true"
  #enable-owasp-modsecurity-crs: "true"
