kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - knative-operator.yml
  - namespace.yml
namespace: knative-operator
commonLabels:
  operator.knative.dev/release: kustomized
