---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
    - dns01:
        cloudflare:
          email: EDITME@example.com
          apiTokenSecretRef:
            name: cert-manager-cloudflare
            key: CF_API_TOKEN
