---
apiVersion: v1
kind: Namespace
metadata:
  name: custom-metrics
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - "$(GRAFANA_HOST)"
      secretName: grafana-tls
  rules:
    - host: "$(GRAFANA_HOST)"
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 3000
            path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $(GRAFANA_STORAGE_SIZE)
