kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../base
  - clusterissuers.yml
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53,1.0.0.1:53,8.8.8.8:53
  target:
    kind: Deployment
    name: cert-manager
