---
# Source: goldilocks/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldilocks-controller
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
---
# Source: goldilocks/templates/dashboard-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldilocks-dashboard
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dashboard
---
# Source: goldilocks/templates/controller-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goldilocks-controller
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
rules:
  - apiGroups:
      - 'apps'
    resources:
      - 'deployments'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - ''
    resources:
      - 'namespaces'
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'autoscaling.k8s.io'
    resources:
      - 'verticalpodautoscalers'
    verbs:
      - 'get'
      - 'list'
      - 'create'
      - 'delete'
      - 'update'
---
# Source: goldilocks/templates/dashboard-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goldilocks-dashboard
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dashboard
rules:
  - apiGroups:
      - 'autoscaling.k8s.io'
    resources:
      - 'verticalpodautoscalers'
    verbs:
      - 'get'
      - 'list'
  - apiGroups:
      - 'apps'
    resources:
      - 'deployments'
    verbs:
      - 'get'
      - 'list'
  - apiGroups:
      - ''
    resources:
      - 'namespaces'
    verbs:
      - 'get'
      - 'list'
---
# Source: goldilocks/templates/controller-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: goldilocks-controller
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goldilocks-controller
subjects:
  - kind: ServiceAccount
    name: goldilocks-controller
    namespace: goldilocks
---
# Source: goldilocks/templates/dashboard-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: goldilocks-dashboard
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goldilocks-dashboard
subjects:
  - kind: ServiceAccount
    name: goldilocks-dashboard
    namespace: goldilocks
---
# Source: goldilocks/templates/dashboard-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: goldilocks-dashboard
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dashboard
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: goldilocks
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/component: dashboard
---
# Source: goldilocks/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldilocks-controller
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goldilocks
      app.kubernetes.io/instance: goldilocks
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goldilocks
        app.kubernetes.io/instance: goldilocks
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: goldilocks-controller
      securityContext:
        {}
      containers:
        - name: goldilocks
          image: "quay.io/fairwinds/goldilocks:v3.1.4"
          imagePullPolicy: Always
          command:
            - /goldilocks
            - controller
            - -v2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10324
          resources:
            limits:
              cpu: 25m
              memory: 32Mi
            requests:
              cpu: 25m
              memory: 32Mi
---
# Source: goldilocks/templates/dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldilocks-dashboard
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-3.2.1
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: goldilocks
      app.kubernetes.io/instance: goldilocks
      app.kubernetes.io/component: dashboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goldilocks
        app.kubernetes.io/instance: goldilocks
        app.kubernetes.io/component: dashboard
    spec:
      serviceAccountName: goldilocks-dashboard
      securityContext:
        {}
      containers:
        - name: goldilocks
          image: "quay.io/fairwinds/goldilocks:v3.1.4"
          imagePullPolicy: Always
          command:
            - /goldilocks
            - dashboard
            - --exclude-containers=linkerd-proxy,istio-proxy
            - -v2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10324
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              cpu: 25m
              memory: 32Mi
            requests:
              cpu: 25m
              memory: 32Mi
