---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 0.21.0  # FIXME hardcoded
  high-availability:
    replicas: 2
  config:
    autoscaler:
      requests-per-second-target-default: "200"
      container-concurrency-target-percentage: "80"
      max-scale: "10"
      initial-scale: "1"
      allow-zero-initial-scale: "false"
      enable-scale-to-zero: "true"
      scale-to-zero-grace-period: "10m"
      scale-to-zero-pod-retention-period: "1h"
      scale-down-delay: "10m"
    letsencrypt:
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-production      
    network:
      autoTLS: Enabled
      httpProtocol: Redirected
      domainTemplate: |-
        {{if index .Annotations "custom-hostname" -}}
          {{- index .Annotations "custom-hostname" -}}
        {{else -}}
          {{- .Name}}-{{.Namespace -}}
        {{end -}}
        .{{.Domain}}
