---
apiVersion: v1
kind: Namespace
metadata:
  name: contour-external
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: contour-internal
  annotations:
    linkerd.io/inject: enabled
