---
apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
 labels:
  istio-injection: enabled
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 0.20.0  # FIXME hardcoded
  high-availability:
    replicas: 2
  config:
    letsencrypt:
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-production      
    network:
      autoTLS: Enabled
      httpProtocol: Redirected
      domainTemplate: |-
        {{if index .Annotations "custom-hostname" -}}
          {{- index .Annotations "custom-hostname" -}}
        {{else -}}
          {{- .Name}}-{{.Namespace -}}
        {{end -}}
        .{{.Domain}}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: knative-serving
spec:
  mtls:
    mode: PERMISSIVE
