---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: zerossl-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    email: EDITME@example.com
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: cert-manager-zerossl
    solvers:
    - dns01:
        cloudflare:
          email: EDITME@example.com
          apiTokenSecretRef:
            name: cert-manager-cloudflare
            key: CF_API_TOKEN
