---
# Source: ambassador/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  namespace: ambassador
spec:
  template:
    spec:
      containers:
        - name: ambassador
          env:
            - name: AMBASSADOR_KNATIVE_SUPPORT
              value: "true"
